/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uig;

/**
 *
 * @author jsfr
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator4 = new javax.swing.JSeparator();
        jDesktopPane_AreaTrabalho = new javax.swing.JDesktopPane();
        jToolBar1 = new javax.swing.JToolBar();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButton_iconEditora = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jButton_iconAutor = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jButton_iconLivro = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jButton_iconExemplar = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        jButton_iconFuncionario = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem_menuCadastroEditora = new javax.swing.JMenuItem();
        jMenuItem_menuAutor = new javax.swing.JMenuItem();
        jMenuItem_AreaConhecimento = new javax.swing.JMenuItem();
        jMenuItem_menuLivro = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem_menuListarEditoras = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SCBEA - Bem Vindo!");

        javax.swing.GroupLayout jDesktopPane_AreaTrabalhoLayout = new javax.swing.GroupLayout(jDesktopPane_AreaTrabalho);
        jDesktopPane_AreaTrabalho.setLayout(jDesktopPane_AreaTrabalhoLayout);
        jDesktopPane_AreaTrabalhoLayout.setHorizontalGroup(
            jDesktopPane_AreaTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 805, Short.MAX_VALUE)
        );
        jDesktopPane_AreaTrabalhoLayout.setVerticalGroup(
            jDesktopPane_AreaTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 429, Short.MAX_VALUE)
        );

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.add(jSeparator1);

        jButton_iconEditora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Editor.png"))); // NOI18N
        jButton_iconEditora.setText("Editora");
        jButton_iconEditora.setFocusable(false);
        jButton_iconEditora.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_iconEditora.setMaximumSize(new java.awt.Dimension(65, 55));
        jButton_iconEditora.setMinimumSize(new java.awt.Dimension(65, 55));
        jButton_iconEditora.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_iconEditora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_iconEditoraActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton_iconEditora);
        jToolBar1.add(jSeparator2);

        jButton_iconAutor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/writer_person_people_man_you_1633.png"))); // NOI18N
        jButton_iconAutor.setText("Autor");
        jButton_iconAutor.setFocusable(false);
        jButton_iconAutor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_iconAutor.setMaximumSize(new java.awt.Dimension(65, 55));
        jButton_iconAutor.setMinimumSize(new java.awt.Dimension(65, 55));
        jButton_iconAutor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_iconAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_iconAutorActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton_iconAutor);
        jToolBar1.add(jSeparator3);

        jButton_iconLivro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/book_7087.png"))); // NOI18N
        jButton_iconLivro.setText("Livro");
        jButton_iconLivro.setFocusable(false);
        jButton_iconLivro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_iconLivro.setMaximumSize(new java.awt.Dimension(65, 55));
        jButton_iconLivro.setMinimumSize(new java.awt.Dimension(65, 55));
        jButton_iconLivro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton_iconLivro);
        jToolBar1.add(jSeparator5);

        jButton_iconExemplar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Exemplar.png"))); // NOI18N
        jButton_iconExemplar.setText("Exemplar");
        jButton_iconExemplar.setFocusable(false);
        jButton_iconExemplar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_iconExemplar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton_iconExemplar);
        jToolBar1.add(jSeparator6);

        jButton_iconFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/User.png"))); // NOI18N
        jButton_iconFuncionario.setText("Funcionário");
        jButton_iconFuncionario.setFocusable(false);
        jButton_iconFuncionario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_iconFuncionario.setMaximumSize(new java.awt.Dimension(65, 55));
        jButton_iconFuncionario.setMinimumSize(new java.awt.Dimension(65, 55));
        jButton_iconFuncionario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton_iconFuncionario);

        jMenu1.setText("Cadastros");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem_menuCadastroEditora.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem_menuCadastroEditora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Editor.png"))); // NOI18N
        jMenuItem_menuCadastroEditora.setText("Editora");
        jMenuItem_menuCadastroEditora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_menuCadastroEditoraActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_menuCadastroEditora);

        jMenuItem_menuAutor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem_menuAutor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/writer_person_people_man_you_1633.png"))); // NOI18N
        jMenuItem_menuAutor.setText("Autor");
        jMenuItem_menuAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_menuAutorActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_menuAutor);

        jMenuItem_AreaConhecimento.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem_AreaConhecimento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Classificacao1.png"))); // NOI18N
        jMenuItem_AreaConhecimento.setText("Area de conhecimento");
        jMenuItem_AreaConhecimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_AreaConhecimentoActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_AreaConhecimento);

        jMenuItem_menuLivro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem_menuLivro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/book_7087.png"))); // NOI18N
        jMenuItem_menuLivro.setText("Livro");
        jMenu1.add(jMenuItem_menuLivro);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Exemplar.png"))); // NOI18N
        jMenuItem1.setText("Exemplar");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Listagem");

        jMenuItem_menuListarEditoras.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem_menuListarEditoras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Listar.png"))); // NOI18N
        jMenuItem_menuListarEditoras.setText("Listar Itens Cadastrados");
        jMenuItem_menuListarEditoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_menuListarEditorasActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem_menuListarEditoras);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Emprestimo / Reserva");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 805, Short.MAX_VALUE)
            .addComponent(jDesktopPane_AreaTrabalho)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane_AreaTrabalho))
        );

        setBounds(0, 0, 821, 549);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem_menuCadastroEditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_menuCadastroEditoraActionPerformed
        // TODO add your handling code here:
        TelaDaEditora TelaDaEditora_Interna = new TelaDaEditora();
        jDesktopPane_AreaTrabalho.add(TelaDaEditora_Interna);
        TelaDaEditora_Interna.setVisible(true);
    }//GEN-LAST:event_jMenuItem_menuCadastroEditoraActionPerformed

    private void jMenuItem_menuListarEditorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_menuListarEditorasActionPerformed
        // TODO add your handling code here:
        Listagem ListagemEditora_Interna = new Listagem();
        jDesktopPane_AreaTrabalho.add(ListagemEditora_Interna);
        ListagemEditora_Interna.setVisible(true);
    }//GEN-LAST:event_jMenuItem_menuListarEditorasActionPerformed

    private void jButton_iconEditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_iconEditoraActionPerformed
        // TODO add your handling code here:
        TelaDaEditora TelaDaEditora_Interna = new TelaDaEditora();
        jDesktopPane_AreaTrabalho.add(TelaDaEditora_Interna);
        TelaDaEditora_Interna.setVisible(true);
    }//GEN-LAST:event_jButton_iconEditoraActionPerformed

    private void jButton_iconAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_iconAutorActionPerformed
        // TODO add your handling code here:
        TelaDoAutor TelaDoAutor = new TelaDoAutor();
        jDesktopPane_AreaTrabalho.add(TelaDoAutor);
        TelaDoAutor.setVisible(true);
    }//GEN-LAST:event_jButton_iconAutorActionPerformed

    private void jMenuItem_menuAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_menuAutorActionPerformed
        // TODO add your handling code here:
        TelaDoAutor TelaDoAutor = new TelaDoAutor();
        jDesktopPane_AreaTrabalho.add(TelaDoAutor);
        TelaDoAutor.setVisible(true);
    }//GEN-LAST:event_jMenuItem_menuAutorActionPerformed

    private void jMenuItem_AreaConhecimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_AreaConhecimentoActionPerformed
        // TODO add your handling code here:
        TelaAreaDeConhecimento TelaAreaDeConhecimento = new TelaAreaDeConhecimento();
        jDesktopPane_AreaTrabalho.add(TelaAreaDeConhecimento);
        TelaAreaDeConhecimento.setVisible(true);
    }//GEN-LAST:event_jMenuItem_AreaConhecimentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_iconAutor;
    private javax.swing.JButton jButton_iconEditora;
    private javax.swing.JButton jButton_iconExemplar;
    private javax.swing.JButton jButton_iconFuncionario;
    private javax.swing.JButton jButton_iconLivro;
    private javax.swing.JDesktopPane jDesktopPane_AreaTrabalho;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem_AreaConhecimento;
    private javax.swing.JMenuItem jMenuItem_menuAutor;
    private javax.swing.JMenuItem jMenuItem_menuCadastroEditora;
    private javax.swing.JMenuItem jMenuItem_menuListarEditoras;
    private javax.swing.JMenuItem jMenuItem_menuLivro;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
