/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uig;

import controle.EditoraControle;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import modelos.classes.Editora;
import modelos.interfaces.ICRUDEditora;
import modelos.utilidades.GeradorID;

/**
 *
 * @author jsfr
 */
public class TelaDaEditora extends javax.swing.JInternalFrame {

    ICRUDEditora objetoControle = new EditoraControle();
    Listagem objetoListar = new Listagem();

    /**
     * Creates new form TelaDaEditora_Interna
     */
    public TelaDaEditora() {
        initComponents();
        DefaultTableModel model = (DefaultTableModel) jTable_tabelaEditoras.getModel();
        jTable_tabelaEditoras.setRowSorter(new TableRowSorter(model));
        try {
            listarDadosNaTela(objetoControle.recuperar());
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(rootPane, erro);
        } finally {
            jButton_incluirEditora.setSelected(false);
        }

    }

 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField_nomeEditora = new javax.swing.JTextField();
        jButton_incluirEditora = new javax.swing.JToggleButton();
        jButton_mostrarEditora = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_tabelaEditoras = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastro de Editora");

        jLabel1.setText("Nome da editora:");

        jButton_incluirEditora.setText("Incluir");
        jButton_incluirEditora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_incluirEditoraActionPerformed(evt);
            }
        });

        jButton_mostrarEditora.setText("Mostrar");
        jButton_mostrarEditora.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton_mostrarEditora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_mostrarEditoraActionPerformed(evt);
            }
        });

        jTable_tabelaEditoras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME DA EDITORA"
            }
        ));
        jTable_tabelaEditoras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_tabelaEditorasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_tabelaEditoras);
        if (jTable_tabelaEditoras.getColumnModel().getColumnCount() > 0) {
            jTable_tabelaEditoras.getColumnModel().getColumn(0).setPreferredWidth(10);
            jTable_tabelaEditoras.getColumnModel().getColumn(1).setPreferredWidth(300);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_nomeEditora, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton_incluirEditora)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_mostrarEditora)))
                .addGap(18, 18, 18))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField_nomeEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_incluirEditora)
                    .addComponent(jButton_mostrarEditora))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE))
        );

        setBounds(150, 20, 490, 398);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_incluirEditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_incluirEditoraActionPerformed
        // TODO add your handling code here:
        try {
            GeradorID GerarID = new GeradorID();
            int id = GerarID.getID();
            GerarID.finalize();
            Editora objetoEditora = new Editora(id, jTextField_nomeEditora.getText());
            objetoControle.incluir(objetoEditora);
            listarDadosNaTela(objetoControle.recuperar());
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null,erro, "Atenção ", JOptionPane.ERROR_MESSAGE);
        } finally {
            jButton_incluirEditora.setSelected(false);
            jTextField_nomeEditora.setText("");
        }
    }//GEN-LAST:event_jButton_incluirEditoraActionPerformed

    private void jButton_mostrarEditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_mostrarEditoraActionPerformed
        // TODO add your handling code here:
        try {
            listarDadosNaTela(objetoControle.recuperar());
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(rootPane, erro);
        }finally{
            jButton_mostrarEditora.setSelected(false);
        }
    }//GEN-LAST:event_jButton_mostrarEditoraActionPerformed

    private void jTable_tabelaEditorasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_tabelaEditorasMouseClicked
        try{
            if (jTable_tabelaEditoras.getSelectedRow()>= 0){
                jTextField_nomeEditora.setText(jTable_tabelaEditoras.getModel().getValueAt(jTable_tabelaEditoras.getSelectedRow() ,1).toString());
            }
        }catch (Exception erro){
            JOptionPane.showMessageDialog(rootPane, "Erro desconhecido");
        }
    }//GEN-LAST:event_jTable_tabelaEditorasMouseClicked
    
    private void listarDadosNaTela(ArrayList<Editora> lista) {
        //Ordenando o Array por nome
        //Criando a Tabela
        DefaultTableModel model = (DefaultTableModel) jTable_tabelaEditoras.getModel();
        jTable_tabelaEditoras.setRowSorter(new TableRowSorter(model));
        //Limpando a tela
        model.setNumRows(0);
        //Correr o ArrayList
        for (int pos = 0; pos < lista.size(); pos++) {
            String[] linha = new String[2];
            Editora aux = lista.get(pos);
            linha[0] = ""+aux.getId();
            linha[1] = aux.getNome();
            model.addRow(linha);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton jButton_incluirEditora;
    private javax.swing.JToggleButton jButton_mostrarEditora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_tabelaEditoras;
    private javax.swing.JTextField jTextField_nomeEditora;
    // End of variables declaration//GEN-END:variables
}
