/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uig;
import controle.AreaDeConhecimentoControle;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import modelos.classes.AreaDeConhecimento;
import modelos.interfaces.ICRUDAreaDeConhecimento;
import modelos.utilidades.GeradorID;

/**
 *
 * @author jsfr
 */
public class TelaAreaDeConhecimento extends javax.swing.JInternalFrame {
    ICRUDAreaDeConhecimento objetoControleArea = new AreaDeConhecimentoControle();
    Listagem objetoListarArea = new Listagem();
    /**
     * Creates new form TelaAreaDeConhecimento
     */
    public TelaAreaDeConhecimento() {
        initComponents();
        
        // Criando tabala Listar Area de Conhecimento
        DefaultTableModel modelAreasDeConhecimento = (DefaultTableModel) jTable_tabelaAreaDeConhecimento.getModel();
        jTable_tabelaAreaDeConhecimento.setRowSorter(new TableRowSorter(modelAreasDeConhecimento));  
        
        try{
            objetoListarArea.listarDadosNaTelaAreaDeConhecimento(objetoControleArea.recuperar(), modelAreasDeConhecimento);
        }catch (Exception erro) {
            JOptionPane.showMessageDialog(rootPane, erro);
        } finally {
            jButton_incluirAreaDeConhecimento.setSelected(false);
            jTextField_codigoAreaConhecimento.setText("");
            jTextField_descricaoAreaConhecimento.setText("");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_codigoAreaConhecimento = new javax.swing.JTextField();
        jTextField_descricaoAreaConhecimento = new javax.swing.JTextField();
        jButton_incluirAreaDeConhecimento = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_tabelaAreaDeConhecimento = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastro Área de Conhecimento");

        jLabel1.setText("Cod. Área Conhecimento:");

        jLabel2.setText("Descrição Área Conhecimento:");

        jButton_incluirAreaDeConhecimento.setText("Incluir");
        jButton_incluirAreaDeConhecimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_incluirAreaDeConhecimentoActionPerformed(evt);
            }
        });

        jTable_tabelaAreaDeConhecimento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "CÓDIGO", "DESCRIÇÃO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_tabelaAreaDeConhecimento);
        if (jTable_tabelaAreaDeConhecimento.getColumnModel().getColumnCount() > 0) {
            jTable_tabelaAreaDeConhecimento.getColumnModel().getColumn(0).setPreferredWidth(5);
            jTable_tabelaAreaDeConhecimento.getColumnModel().getColumn(1).setPreferredWidth(30);
            jTable_tabelaAreaDeConhecimento.getColumnModel().getColumn(2).setPreferredWidth(270);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField_codigoAreaConhecimento, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(191, Short.MAX_VALUE))
                            .addComponent(jTextField_descricaoAreaConhecimento)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton_incluirAreaDeConhecimento))))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_codigoAreaConhecimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_descricaoAreaConhecimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_incluirAreaDeConhecimento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE))
        );

        setBounds(150, 20, 490, 398);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_incluirAreaDeConhecimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_incluirAreaDeConhecimentoActionPerformed
        try {
            // TODO add your handling code here:
            GeradorID gerarID = new GeradorID();
            AreaDeConhecimento objetoAreaDeConhecimento = new AreaDeConhecimento(gerarID.getID(), jTextField_codigoAreaConhecimento.getText(),jTextField_descricaoAreaConhecimento.getText());
            objetoControleArea.incluir(objetoAreaDeConhecimento);
            // Criando tabala Listar Area de Conhecimento
            DefaultTableModel modelAreasDeConhecimento = (DefaultTableModel) jTable_tabelaAreaDeConhecimento.getModel();
            jTable_tabelaAreaDeConhecimento.setRowSorter(new TableRowSorter(modelAreasDeConhecimento));  
            objetoListarArea.listarDadosNaTelaAreaDeConhecimento(objetoControleArea.recuperar(), modelAreasDeConhecimento);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(rootPane, erro);
        }finally{
            jTextField_codigoAreaConhecimento.setText("");
            jTextField_descricaoAreaConhecimento.setText("");
            jButton_incluirAreaDeConhecimento.setSelected(false);
        }
        
    }//GEN-LAST:event_jButton_incluirAreaDeConhecimentoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_incluirAreaDeConhecimento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_tabelaAreaDeConhecimento;
    private javax.swing.JTextField jTextField_codigoAreaConhecimento;
    private javax.swing.JTextField jTextField_descricaoAreaConhecimento;
    // End of variables declaration//GEN-END:variables
}
