/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uig;

import javax.swing.JOptionPane;
import controle.ColaboradorControle;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import modelos.classes.Colaborador;
import modelos.interfaces.ICRUDColaborador;
import modelos.utilidades.GeradorID;

/**
 *
 * @author jsfr
 */
public class TelaDoColaborador extends javax.swing.JInternalFrame {

    ICRUDColaborador objetoControle = new ColaboradorControle();
    Listagem objetoListarColaborador = new Listagem();

    /**
     * Creates new form TelaDoColaborador
     */
    public TelaDoColaborador() {
        initComponents();
        jTextField_senha.setEnabled(false);
        jButton_editar.setEnabled(false);
        jButton_excluir.setEnabled(false);
        jTextField_numeroOAB.setEnabled(false);

        // Criando Tabela Listar Colaboradores
        DefaultTableModel modelColaboradores = (DefaultTableModel) jTable_tabelaColaboradores.getModel();
        jTable_tabelaColaboradores.setRowSorter(new TableRowSorter(modelColaboradores));

        try {
            objetoListarColaborador.listarDadosNaTelaColaborador(objetoControle.recuperar(), modelColaboradores);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(rootPane, erro);
        } finally {

        }
    }

    private void limparTela() {
        jTextField_matricula.setText("");
        jTextField_nome.setText("");
        jTextField_numeroOAB.setText("");
        jTextField_cpf.setText("");
        jTextField_eMail.setText("");
        jTextField_telefone.setText("");
        jTextField_senha.setText("");
        
        jButton_salvar.setEnabled(true);
        jButton_editar.setEnabled(false);
        jButton_excluir.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jCheckBox_statusColaborador = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jComboBox_tipoColaborador = new javax.swing.JComboBox<>();
        jTextField_matricula = new javax.swing.JTextField();
        jTextField_nome = new javax.swing.JTextField();
        jTextField_eMail = new javax.swing.JTextField();
        jTextField_telefone = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_tabelaColaboradores = new javax.swing.JTable();
        jButton_salvar = new javax.swing.JButton();
        jButton_editar = new javax.swing.JButton();
        jButton_excluir = new javax.swing.JButton();
        jCheckBox_usuário = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jTextField_senha = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField_cpf = new javax.swing.JTextField();
        jButton_limpar = new javax.swing.JButton();
        jTextField_numeroOAB = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastro do Colaborador");
        setPreferredSize(new java.awt.Dimension(862, 813));

        jLabel1.setText("Matricula:");

        jLabel2.setText("Nome:");

        jLabel3.setText("AOB:");

        jLabel4.setText("e-Mail:");

        jLabel5.setText("Telefone:");

        jCheckBox_statusColaborador.setSelected(true);
        jCheckBox_statusColaborador.setText("Ativo");
        jCheckBox_statusColaborador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_statusColaboradorActionPerformed(evt);
            }
        });

        jLabel6.setText("Tipo Colaborador:");

        jComboBox_tipoColaborador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FUNCIONARIO", "ESTAGIARIO", "ADVOGADO" }));
        jComboBox_tipoColaborador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_tipoColaboradorActionPerformed(evt);
            }
        });

        jTable_tabelaColaboradores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "MATRICULA", "NOME", "OAB", "CPF", "e-MAIL", "TELEFONE", "TIPO", "STATUS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_tabelaColaboradores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_tabelaColaboradoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_tabelaColaboradores);
        if (jTable_tabelaColaboradores.getColumnModel().getColumnCount() > 0) {
            jTable_tabelaColaboradores.getColumnModel().getColumn(0).setPreferredWidth(5);
            jTable_tabelaColaboradores.getColumnModel().getColumn(1).setPreferredWidth(6);
            jTable_tabelaColaboradores.getColumnModel().getColumn(2).setPreferredWidth(70);
            jTable_tabelaColaboradores.getColumnModel().getColumn(3).setPreferredWidth(5);
            jTable_tabelaColaboradores.getColumnModel().getColumn(4).setPreferredWidth(12);
            jTable_tabelaColaboradores.getColumnModel().getColumn(5).setPreferredWidth(30);
            jTable_tabelaColaboradores.getColumnModel().getColumn(6).setPreferredWidth(10);
            jTable_tabelaColaboradores.getColumnModel().getColumn(7).setPreferredWidth(10);
            jTable_tabelaColaboradores.getColumnModel().getColumn(8).setPreferredWidth(10);
        }

        jButton_salvar.setText("Incluir");
        jButton_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_salvarActionPerformed(evt);
            }
        });

        jButton_editar.setText("Editar");
        jButton_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_editarActionPerformed(evt);
            }
        });

        jButton_excluir.setText("Excluir");
        jButton_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_excluirActionPerformed(evt);
            }
        });

        jCheckBox_usuário.setText("Usuário");
        jCheckBox_usuário.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_usuárioActionPerformed(evt);
            }
        });

        jLabel7.setText("Senha:");

        jLabel8.setText("CPF:");

        jButton_limpar.setText("Limpar");
        jButton_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_limparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton_limpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_excluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_editar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_salvar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jComboBox_tipoColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_numeroOAB, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_cpf))
                            .addComponent(jTextField_eMail)
                            .addComponent(jTextField_nome)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel7)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField_senha)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jCheckBox_statusColaborador)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCheckBox_usuário)))))
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField_matricula, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_matricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox_tipoColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField_numeroOAB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_eMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox_usuário)
                    .addComponent(jCheckBox_statusColaborador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_salvar)
                    .addComponent(jButton_editar)
                    .addComponent(jButton_excluir)
                    .addComponent(jButton_limpar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE))
        );

        setBounds(150, 20, 562, 509);
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox_statusColaboradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_statusColaboradorActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jCheckBox_statusColaboradorActionPerformed

    private void jCheckBox_usuárioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_usuárioActionPerformed
        // TODO add your handling code here:
        if (jCheckBox_usuário.isSelected()) {
            jTextField_senha.setEnabled(true);
        } else {
            jTextField_senha.setEnabled(false);
        }

    }//GEN-LAST:event_jCheckBox_usuárioActionPerformed

    private void jTable_tabelaColaboradoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_tabelaColaboradoresMouseClicked
        try {
            if (jTable_tabelaColaboradores.getSelectedRow() >= 0) {
                jTextField_matricula.setText(jTable_tabelaColaboradores.getModel().getValueAt(jTable_tabelaColaboradores.getSelectedRow(), 1).toString());
                jTextField_nome.setText(jTable_tabelaColaboradores.getModel().getValueAt(jTable_tabelaColaboradores.getSelectedRow(), 2).toString());
                jTextField_numeroOAB.setText(jTable_tabelaColaboradores.getModel().getValueAt(jTable_tabelaColaboradores.getSelectedRow(), 3).toString());
                jTextField_cpf.setText(jTable_tabelaColaboradores.getModel().getValueAt(jTable_tabelaColaboradores.getSelectedRow(), 4).toString());
                jTextField_eMail.setText(jTable_tabelaColaboradores.getModel().getValueAt(jTable_tabelaColaboradores.getSelectedRow(), 5).toString());
                jTextField_telefone.setText(jTable_tabelaColaboradores.getModel().getValueAt(jTable_tabelaColaboradores.getSelectedRow(), 6).toString());
                String tipo=jTable_tabelaColaboradores.getModel().getValueAt(jTable_tabelaColaboradores.getSelectedRow(), 7).toString();
                switch (tipo){
                    case "FUNCIONARIO": jComboBox_tipoColaborador.setSelectedIndex(0);
                    break;
                    case "ESTAGIARIO": jComboBox_tipoColaborador.setSelectedIndex(1);
                    break;
                    case "ADVOGADO": jComboBox_tipoColaborador.setSelectedIndex(2);
                }    
                tipo=jTable_tabelaColaboradores.getModel().getValueAt(jTable_tabelaColaboradores.getSelectedRow(), 8).toString();
                if (tipo.equalsIgnoreCase("ATIVO")){
                    jCheckBox_statusColaborador.setSelected(true);
                }
                else{ 
                    jCheckBox_statusColaborador.setSelected(false);
                }
                jButton_editar.setEnabled(true);
                jButton_excluir.setEnabled(true);
                jButton_limpar.setEnabled(true);
                jButton_salvar.setEnabled(false);
            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(rootPane, "Erro desconhecido");
        }
    }//GEN-LAST:event_jTable_tabelaColaboradoresMouseClicked

    private void jButton_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_salvarActionPerformed
        // TODO add your handling code here:
        try {
            GeradorID GerarID = new GeradorID();
            int id = GerarID.getID();
            String status = "";
            if (jCheckBox_statusColaborador.isSelected()) {
                status = "ATIVO";
            } else {
                status = "INATIVO";
            }
            GerarID.finalize();
            Colaborador objetoColaborador = new Colaborador(id,
                    Integer.parseInt(jTextField_matricula.getText()),
                    jTextField_nome.getText(),
                    Integer.parseInt(jTextField_numeroOAB.getText()),
                    Long.parseLong(jTextField_cpf.getText()),
                    jTextField_eMail.getText(),
                    Long.parseLong(jTextField_telefone.getText()),
                    jComboBox_tipoColaborador.getSelectedItem().toString(),
                    status);
            objetoControle.incluir(objetoColaborador);
            // Criando Tabela Listar Colaboradores
            DefaultTableModel modelColaboradores = (DefaultTableModel) jTable_tabelaColaboradores.getModel();
            jTable_tabelaColaboradores.setRowSorter(new TableRowSorter(modelColaboradores));
            objetoListarColaborador.listarDadosNaTelaColaborador(objetoControle.recuperar(), modelColaboradores);
            limparTela();
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro, "Atenção ", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton_salvarActionPerformed

    private void jButton_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_excluirActionPerformed
        // TODO add your handling code here:
        try {
            objetoControle.excluir(Integer.parseInt(jTextField_cpf.getText()));

            // Criando Tabela Listar Colaboradores
            DefaultTableModel modelColaboradores = (DefaultTableModel) jTable_tabelaColaboradores.getModel();
            jTable_tabelaColaboradores.setRowSorter(new TableRowSorter(modelColaboradores));
            objetoListarColaborador.listarDadosNaTelaColaborador(objetoControle.recuperar(), modelColaboradores);
            limparTela();
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, ui);
        }
    }//GEN-LAST:event_jButton_excluirActionPerformed

    private void jButton_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_limparActionPerformed
        // TODO add your handling code here:
        limparTela();
    }//GEN-LAST:event_jButton_limparActionPerformed

    private void jComboBox_tipoColaboradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_tipoColaboradorActionPerformed
        // TODO add your handling code here:
        if(jComboBox_tipoColaborador.getSelectedItem().toString().equalsIgnoreCase("ADVOGADO")){
            jTextField_numeroOAB.setEnabled(true);
        }
        else{
            jTextField_numeroOAB.setEnabled(false);
        }
    }//GEN-LAST:event_jComboBox_tipoColaboradorActionPerformed

    private void jButton_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_editarActionPerformed
        // TODO add your handling code here:
        try {
            String status = "";
            if (jCheckBox_statusColaborador.isSelected()) {
                status = "ATIVO";
            } else {
                status = "INATIVO";
            }
            Colaborador objetoColaborador = new Colaborador(Integer.parseInt(jTable_tabelaColaboradores.getModel().getValueAt(jTable_tabelaColaboradores.getSelectedRow(), 0).toString()),
                    Integer.parseInt(jTextField_matricula.getText()),
                    jTextField_nome.getText(),
                    Integer.parseInt(jTextField_numeroOAB.getText()),
                    Long.parseLong(jTextField_cpf.getText()),
                    jTextField_eMail.getText(),
                    Long.parseLong(jTextField_telefone.getText()),
                    jComboBox_tipoColaborador.getSelectedItem().toString(),
                    status);
            objetoControle.editar(objetoColaborador);
            // Criando Tabela Listar Colaboradores
            DefaultTableModel modelColaboradores = (DefaultTableModel) jTable_tabelaColaboradores.getModel();
            jTable_tabelaColaboradores.setRowSorter(new TableRowSorter(modelColaboradores));
            objetoListarColaborador.listarDadosNaTelaColaborador(objetoControle.recuperar(), modelColaboradores);
            limparTela();
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro, "Atenção ", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jButton_editarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_editar;
    private javax.swing.JButton jButton_excluir;
    private javax.swing.JButton jButton_limpar;
    private javax.swing.JButton jButton_salvar;
    private javax.swing.JCheckBox jCheckBox_statusColaborador;
    private javax.swing.JCheckBox jCheckBox_usuário;
    private javax.swing.JComboBox<String> jComboBox_tipoColaborador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_tabelaColaboradores;
    private javax.swing.JTextField jTextField_cpf;
    private javax.swing.JTextField jTextField_eMail;
    private javax.swing.JTextField jTextField_matricula;
    private javax.swing.JTextField jTextField_nome;
    private javax.swing.JTextField jTextField_numeroOAB;
    private javax.swing.JTextField jTextField_senha;
    private javax.swing.JTextField jTextField_telefone;
    // End of variables declaration//GEN-END:variables
}
