/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uig;

import controle.AutorControle;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import modelos.classes.Autor;
import modelos.interfaces.ICRUDAutor;
import modelos.utilidades.GeradorID;

/**
 *
 * @author jsfr
 */
public class TelaDoAutor extends javax.swing.JInternalFrame {

    ICRUDAutor objetoControle = new AutorControle();
    
    /**
     * Creates new form TelaDoAutor
     */
    public TelaDoAutor() {
        initComponents();
        //Criando tabela de autores
        DefaultTableModel model = (DefaultTableModel) jTable_tabelaAutores.getModel();
        jTable_tabelaAutores.setRowSorter(new TableRowSorter(model));
        try {
            listarDadosNaTela(objetoControle.recuperar());
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(rootPane, erro);
        } finally {
            jButton_incluirAutor.setSelected(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField_nomeAutor = new javax.swing.JTextField();
        jButton_incluirAutor = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_tabelaAutores = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastro de Autor");
        setVisible(false);

        jLabel1.setText("Nome do Autor:");

        jButton_incluirAutor.setText("Incluir");
        jButton_incluirAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_incluirAutorActionPerformed(evt);
            }
        });

        jTable_tabelaAutores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME DO AUTOR"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_tabelaAutores);
        if (jTable_tabelaAutores.getColumnModel().getColumnCount() > 0) {
            jTable_tabelaAutores.getColumnModel().getColumn(0).setPreferredWidth(10);
            jTable_tabelaAutores.getColumnModel().getColumn(1).setPreferredWidth(300);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_nomeAutor))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton_incluirAutor)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_nomeAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_incluirAutor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE))
        );

        setBounds(150, 20, 490, 398);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_incluirAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_incluirAutorActionPerformed
        // TODO add your handling code here:
        try {
            GeradorID GerarID = new GeradorID();
            int id = GerarID.getID();
            GerarID.finalize();
            Autor objetoAutor = new Autor(id, jTextField_nomeAutor.getText());
            objetoControle.incluir(objetoAutor);
            listarDadosNaTela(objetoControle.recuperar());
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(rootPane, erro);
        } finally {
            jButton_incluirAutor.setSelected(false);
            jTextField_nomeAutor.setText("");
        }
    }//GEN-LAST:event_jButton_incluirAutorActionPerformed

    private void listarDadosNaTela(ArrayList<Autor> lista) {
        //Ordenando o Array por nome
        //Criando a Tabela
        DefaultTableModel model = (DefaultTableModel) jTable_tabelaAutores.getModel();
        jTable_tabelaAutores.setRowSorter(new TableRowSorter(model));
        //Limpando a tela
        model.setNumRows(0);
        //Correr o ArrayList
        for (int pos = 0; pos < lista.size(); pos++) {
            String[] linha = new String[2];
            Autor aux = lista.get(pos);
            linha[0] = "" + aux.getId();
            linha[1] = aux.getNome();
            model.addRow(linha);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_incluirAutor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_tabelaAutores;
    private javax.swing.JTextField jTextField_nomeAutor;
    // End of variables declaration//GEN-END:variables
}
